spring.application.name=telegram_bot_dars
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/pochta_bot
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database=postgresql
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



